insert into burgers (burger_name, devoured) values ('Beer - Mcauslan Apricot Burger', true);
insert into burgers (burger_name, devoured) values ('Pepper - Red Bell Burger', true);
insert into burgers (burger_name, devoured) values ('Squash - Sunburst Burger', true);
insert into burgers (burger_name, devoured) values ('Pasta - Rotini, Colour, Dry Burger', false);
insert into burgers (burger_name, devoured) values ('Pasta - Fettuccine, Dry Burger', true);
insert into burgers (burger_name, devoured) values ('Wine - Sake Burger', true);
insert into burgers (burger_name, devoured) values ('Tomatoes - Cherry, Yellow Burger', true);
insert into burgers (burger_name, devoured) values ('Trout - Hot Smkd, Dbl Fillet Burger', false);
insert into burgers (burger_name, devoured) values ('Hot Choc Burger', false);
insert into burgers (burger_name, devoured) values ('Vaccum Bag Burger', false);
insert into burgers (burger_name, devoured) values ('Pop - Club Soda Burger', false);
insert into burgers (burger_name, devoured) values ('Sea Bass - Fillet Burger', false);
insert into burgers (burger_name, devoured) values ('Cleaner - Comet Burger', false);
insert into burgers (burger_name, devoured) values ('Mustard - Pommery Burger', false);
insert into burgers (burger_name, devoured) values ('Wine - Pinot Noir Latour Burger', false);
insert into burgers (burger_name, devoured) values ('Tabasco Sauce Burger', true);
insert into burgers (burger_name, devoured) values ('Cabbage - Red Burger', true);
insert into burgers (burger_name, devoured) values ('Wine - White, Colubia Cresh Burger', false);
insert into burgers (burger_name, devoured) values ('Beef Flat Iron Steak Burger', true);
insert into burgers (burger_name, devoured) values ('Mix Pina Colada Burger', true);